project:
  title: "curso-quarto-tfm"
  output-dir: "04_outputs"

## Bibliografía ---------------
bibliography: references.bib
biblio-title: "Referencias"
link-citations: true
link-bibliography: true
cite-method: biblatex
biblio-style: apa

## Fuentes/colores ------------
mainfont: Times New Roman
fontsize: 12pt
citecolor: purple
toccolor: teal
linkcolor: teal
urlcolor: magenta

## Format ---------------------
geometry: 
    - margin = 1in
    - heightrounded
linestretch: 1.5
number-sections: true
toc: true
lof: true
toc-title: "Contenidos"
lang: es

## Figuras --------------------
fig-align: center
fig-pos: "bt!"
crossref: 
    fig-title: "Fig."
    fig-prefix: "Fig."
    title-delim: "."
    lof-title: "Lista de Figuras"

## Codigo ---------------------
execute: 
  echo: false
  warning: false
  freeze: auto

## PDF formato -----------------
format: 
    pdf:
        documentclass: scrreprt
        template-partials: 
            - "02_templates/before-body.tex"
            - "02_templates/_titlepage.tex"
        include-in-header: 
            - "02_templates/in-header.tex"